In [1]:
import numpy as np 
import pandas as pd

In [9]:
import pandas as pd

data = {
    "RaceID": range(3001, 3051),
    "GrandPrix": [
        "Bahrain", "Saudi Arabia", "Australia", "Azerbaijan", "Miami",
        "Monaco", "Spain", "Canada", "Austria", "Silverstone"
    ] * 5,
    "Year": [2021, 2022, 2023, 2024, 2025] * 10,
    "Driver": [
        "Max Verstappen", "Lewis Hamilton", "Charles Leclerc", "Sergio Perez", "Lando Norris",
        "Carlos Sainz", "George Russell", "Fernando Alonso", "Oscar Piastri", "Esteban Ocon"
    ] * 5,
    "Team": [
        "Red Bull", "Mercedes", "Ferrari", "Red Bull", "McLaren",
        "Ferrari", "Mercedes", "Aston Martin", "McLaren", "Alpine"
    ] * 5,
    "Position": [1,2,3,4,5,6,7,8,9,10] * 5,
    "Points": [25,18,15,12,10,8,6,4,2,1] * 5,
    "FastestLap": [0,1,0,0,1,0,1,0,0,1] * 5,
    "PitStops": [2,3,1,2,2,3,1,2,3,2] * 5,
    "Weather": ["Sunny","Rain","Cloudy","Sunny","Rain",
                "Cloudy","Sunny","Rain","Cloudy","Sunny"] * 5
}

df= pd.DataFrame(data)
df

,RaceID,GrandPrix,Year,Driver,Team,Position,Points,FastestLap,PitStops,Weather
0,3001,Bahrain,2021,Max Verstappen,Red Bull,1,25,0,2,Sunny
1,3002,Saudi Arabia,2022,Lewis Hamilton,Mercedes,2,18,1,3,Rain
2,3003,Australia,2023,Charles Leclerc,Ferrari,3,15,0,1,Cloudy
3,3004,Azerbaijan,2024,Sergio Perez,Red Bull,4,12,0,2,Sunny
4,3005,Miami,2025,Lando Norris,McLaren,5,10,1,2,Rain
5,3006,Monaco,2021,Carlos Sainz,Ferrari,6,8,0,3,Cloudy
6,3007,Spain,2022,George Russell,Mercedes,7,6,1,1,Sunny
7,3008,Canada,2023,Fernando Alonso,Aston Martin,8,4,0,2,Rain
8,3009,Austria,2024,Oscar Piastri,McLaren,9,2,0,3,Cloudy
9,3010,Silverstone,2025,Esteban Ocon,Alpine,10,1,1,2,Sunny
10,3011,Bahrain,2021,Max Verstappen,Red Bull,1,25,0,2,Sunny
11,3012,Saudi Arabia,2022,Lewis Hamilton,Mercedes,2,18,1,3,Rain
12,3013,Australia,2023,Charles Leclerc,Ferrari,3,15,0,1,Cloudy
13,3014,Azerbaijan,2024,Sergio Perez,Red Bull,4,12,0,2,Sunny
14,3015,Miami,2025,Lando Norris,McLaren,5,10,1,2,Rain
15,3016,Monaco,2021,Carlos Sainz,Ferrari,6,8,0,3,Cloudy
16,3017,Spain,2022,George Russell,Mercedes,7,6,1,1,Sunny
17,3018,Canada,2023,Fernando Alonso,Aston Martin,8,4,0,2,Rain
18,3019,Austria,2024,Oscar Piastri,McLaren,9,2,0,3,Cloudy
19,3020,Silverstone,2025,Esteban Ocon,Alpine,10,1,1,2,Sunny
20,3021,Bahrain,2021,Max Verstappen,Red Bull,1,25,0,2,Sunny
21,3022,Saudi Arabia,2022,Lewis Hamilton,Mercedes,2,18,1,3,Rain
22,3023,Australia,2023,Charles Leclerc,Ferrari,3,15,0,1,Cloudy
23,3024,Azerbaijan,2024,Sergio Perez,Red Bull,4,12,0,2,Sunny
24,3025,Miami,2025,Lando Norris,McLaren,5,10,1,2,Rain
25,3026,Monaco,2021,Carlos Sainz,Ferrari,6,8,0,3,Cloudy
26,3027,Spain,2022,George Russell,Mercedes,7,6,1,1,Sunny
27,3028,Canada,2023,Fernando Alonso,Aston Martin,8,4,0,2,Rain
28,3029,Austria,2024,Oscar Piastri,McLaren,9,2,0,3,Cloudy
29,3030,Silverstone,2025,Esteban Ocon,Alpine,10,1,1,2,Sunny
30,3031,Bahrain,2021,Max Verstappen,Red Bull,1,25,0,2,Sunny
31,3032,Saudi Arabia,2022,Lewis Hamilton,Mercedes,2,18,1,3,Rain
32,3033,Australia,2023,Charles Leclerc,Ferrari,3,15,0,1,Cloudy
33,3034,Azerbaijan,2024,Sergio Perez,Red Bull,4,12,0,2,Sunny
34,3035,Miami,2025,Lando Norris,McLaren,5,10,1,2,Rain
35,3036,Monaco,2021,Carlos Sainz,Ferrari,6,8,0,3,Cloudy
36,3037,Spain,2022,George Russell,Mercedes,7,6,1,1,Sunny
37,3038,Canada,2023,Fernando Alonso,Aston Martin,8,4,0,2,Rain
38,3039,Austria,2024,Oscar Piastri,McLaren,9,2,0,3,Cloudy
39,3040,Silverstone,2025,Esteban Ocon,Alpine,10,1,1,2,Sunny
40,3041,Bahrain,2021,Max Verstappen,Red Bull,1,25,0,2,Sunny
41,3042,Saudi Arabia,2022,Lewis Hamilton,Mercedes,2,18,1,3,Rain
42,3043,Australia,2023,Charles Leclerc,Ferrari,3,15,0,1,Cloudy
43,3044,Azerbaijan,2024,Sergio Perez,Red Bull,4,12,0,2,Sunny
44,3045,Miami,2025,Lando Norris,McLaren,5,10,1,2,Rain
45,3046,Monaco,2021,Carlos Sainz,Ferrari,6,8,0,3,Cloudy
46,3047,Spain,2022,George Russell,Mercedes,7,6,1,1,Sunny
47,3048,Canada,2023,Fernando Alonso,Aston Martin,8,4,0,2,Rain
48,3049,Austria,2024,Oscar Piastri,McLaren,9,2,0,3,Cloudy
49,3050,Silverstone,2025,Esteban Ocon,Alpine,10,1,1,2,Sunny

In [11]:
pd.pivot_table(df,values='Points',index='RaceID',columns='Year')

Year    2021  2022  2023  2024  2025
RaceID
3001    25.0   NaN   NaN   NaN   NaN
3002     NaN  18.0   NaN   NaN   NaN
3003     NaN   NaN  15.0   NaN   NaN
3004     NaN   NaN   NaN  12.0   NaN
3005     NaN   NaN   NaN   NaN  10.0
3006     8.0   NaN   NaN   NaN   NaN
3007     NaN   6.0   NaN   NaN   NaN
3008     NaN   NaN   4.0   NaN   NaN
3009     NaN   NaN   NaN   2.0   NaN
3010     NaN   NaN   NaN   NaN   1.0
3011    25.0   NaN   NaN   NaN   NaN
3012     NaN  18.0   NaN   NaN   NaN
3013     NaN   NaN  15.0   NaN   NaN
3014     NaN   NaN   NaN  12.0   NaN
3015     NaN   NaN   NaN   NaN  10.0
3016     8.0   NaN   NaN   NaN   NaN
3017     NaN   6.0   NaN   NaN   NaN
3018     NaN   NaN   4.0   NaN   NaN
3019     NaN   NaN   NaN   2.0   NaN
3020     NaN   NaN   NaN   NaN   1.0
3021    25.0   NaN   NaN   NaN   NaN
3022     NaN  18.0   NaN   NaN   NaN
3023     NaN   NaN  15.0   NaN   NaN
3024     NaN   NaN   NaN  12.0   NaN
3025     NaN   NaN   NaN   NaN  10.0
3026     8.0   NaN   NaN   NaN   NaN
3027     NaN   6.0   NaN   NaN   NaN
3028     NaN   NaN   4.0   NaN   NaN
3029     NaN   NaN   NaN   2.0   NaN
3030     NaN   NaN   NaN   NaN   1.0
3031    25.0   NaN   NaN   NaN   NaN
3032     NaN  18.0   NaN   NaN   NaN
3033     NaN   NaN  15.0   NaN   NaN
3034     NaN   NaN   NaN  12.0   NaN
3035     NaN   NaN   NaN   NaN  10.0
3036     8.0   NaN   NaN   NaN   NaN
3037     NaN   6.0   NaN   NaN   NaN
3038     NaN   NaN   4.0   NaN   NaN
3039     NaN   NaN   NaN   2.0   NaN
3040     NaN   NaN   NaN   NaN   1.0
3041    25.0   NaN   NaN   NaN   NaN
3042     NaN  18.0   NaN   NaN   NaN
3043     NaN   NaN  15.0   NaN   NaN
3044     NaN   NaN   NaN  12.0   NaN
3045     NaN   NaN   NaN   NaN  10.0
3046     8.0   NaN   NaN   NaN   NaN
3047     NaN   6.0   NaN   NaN   NaN
3048     NaN   NaN   4.0   NaN   NaN
3049     NaN   NaN   NaN   2.0   NaN
3050     NaN   NaN   NaN   NaN   1.0

In [12]:
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   RaceID      50 non-null     int64
 1   GrandPrix   50 non-null     object
 2   Year        50 non-null     int64
 3   Driver      50 non-null     object
 4   Team        50 non-null     object
 5   Position    50 non-null     int64
 6   Points      50 non-null     int64
 7   FastestLap  50 non-null     int64
 8   PitStops    50 non-null     int64
 9   Weather     50 non-null     object
dtypes: int64(6), object(4)
memory usage: 4.0+ KB

,RaceID,GrandPrix,Year,Driver,Team,Position,Points,FastestLap,PitStops,Weather
count,50.00000,50,50.000000,50,50,50.000000,50.000000,50.000000,50.000000,50
unique,NaN,10,NaN,10,6,NaN,NaN,NaN,NaN,3
top,NaN,Bahrain,NaN,Max Verstappen,Red Bull,NaN,NaN,NaN,NaN,Sunny
freq,NaN,5,NaN,5,10,NaN,NaN,NaN,NaN,20
mean,3025.50000,NaN,2023.000000,NaN,NaN,5.500000,10.100000,0.400000,2.100000,NaN
std,14.57738,NaN,1.428571,NaN,NaN,2.901442,7.276605,0.494872,0.707107,NaN
min,3001.00000,NaN,2021.000000,NaN,NaN,1.000000,1.000000,0.000000,1.000000,NaN
25%,3013.25000,NaN,2022.000000,NaN,NaN,3.000000,4.000000,0.000000,2.000000,NaN
50%,3025.50000,NaN,2023.000000,NaN,NaN,5.500000,9.000000,0.000000,2.000000,NaN
75%,3037.75000,NaN,2024.000000,NaN,NaN,8.000000,15.000000,1.000000,3.000000,NaN
max,3050.00000,NaN,2025.000000,NaN,NaN,10.000000,25.000000,1.000000,3.000000,NaN

In [13]:
pd.pivot_table(df,values=['Points','PitStops'],index='RaceID',columns='Year')

       PitStops                     Points
Year       2021 2022 2023 2024 2025   2021  2022  2023  2024  2025
RaceID
3001        2.0  NaN  NaN  NaN  NaN   25.0   NaN   NaN   NaN   NaN
3002        NaN  3.0  NaN  NaN  NaN    NaN  18.0   NaN   NaN   NaN
3003        NaN  NaN  1.0  NaN  NaN    NaN   NaN  15.0   NaN   NaN
3004        NaN  NaN  NaN  2.0  NaN    NaN   NaN   NaN  12.0   NaN
3005        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN  10.0
3006        3.0  NaN  NaN  NaN  NaN    8.0   NaN   NaN   NaN   NaN
3007        NaN  1.0  NaN  NaN  NaN    NaN   6.0   NaN   NaN   NaN
3008        NaN  NaN  2.0  NaN  NaN    NaN   NaN   4.0   NaN   NaN
3009        NaN  NaN  NaN  3.0  NaN    NaN   NaN   NaN   2.0   NaN
3010        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN   1.0
3011        2.0  NaN  NaN  NaN  NaN   25.0   NaN   NaN   NaN   NaN
3012        NaN  3.0  NaN  NaN  NaN    NaN  18.0   NaN   NaN   NaN
3013        NaN  NaN  1.0  NaN  NaN    NaN   NaN  15.0   NaN   NaN
3014        NaN  NaN  NaN  2.0  NaN    NaN   NaN   NaN  12.0   NaN
3015        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN  10.0
3016        3.0  NaN  NaN  NaN  NaN    8.0   NaN   NaN   NaN   NaN
3017        NaN  1.0  NaN  NaN  NaN    NaN   6.0   NaN   NaN   NaN
3018        NaN  NaN  2.0  NaN  NaN    NaN   NaN   4.0   NaN   NaN
3019        NaN  NaN  NaN  3.0  NaN    NaN   NaN   NaN   2.0   NaN
3020        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN   1.0
3021        2.0  NaN  NaN  NaN  NaN   25.0   NaN   NaN   NaN   NaN
3022        NaN  3.0  NaN  NaN  NaN    NaN  18.0   NaN   NaN   NaN
3023        NaN  NaN  1.0  NaN  NaN    NaN   NaN  15.0   NaN   NaN
3024        NaN  NaN  NaN  2.0  NaN    NaN   NaN   NaN  12.0   NaN
3025        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN  10.0
3026        3.0  NaN  NaN  NaN  NaN    8.0   NaN   NaN   NaN   NaN
3027        NaN  1.0  NaN  NaN  NaN    NaN   6.0   NaN   NaN   NaN
3028        NaN  NaN  2.0  NaN  NaN    NaN   NaN   4.0   NaN   NaN
3029        NaN  NaN  NaN  3.0  NaN    NaN   NaN   NaN   2.0   NaN
3030        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN   1.0
3031        2.0  NaN  NaN  NaN  NaN   25.0   NaN   NaN   NaN   NaN
3032        NaN  3.0  NaN  NaN  NaN    NaN  18.0   NaN   NaN   NaN
3033        NaN  NaN  1.0  NaN  NaN    NaN   NaN  15.0   NaN   NaN
3034        NaN  NaN  NaN  2.0  NaN    NaN   NaN   NaN  12.0   NaN
3035        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN  10.0
3036        3.0  NaN  NaN  NaN  NaN    8.0   NaN   NaN   NaN   NaN
3037        NaN  1.0  NaN  NaN  NaN    NaN   6.0   NaN   NaN   NaN
3038        NaN  NaN  2.0  NaN  NaN    NaN   NaN   4.0   NaN   NaN
3039        NaN  NaN  NaN  3.0  NaN    NaN   NaN   NaN   2.0   NaN
3040        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN   1.0
3041        2.0  NaN  NaN  NaN  NaN   25.0   NaN   NaN   NaN   NaN
3042        NaN  3.0  NaN  NaN  NaN    NaN  18.0   NaN   NaN   NaN
3043        NaN  NaN  1.0  NaN  NaN    NaN   NaN  15.0   NaN   NaN
3044        NaN  NaN  NaN  2.0  NaN    NaN   NaN   NaN  12.0   NaN
3045        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN  10.0
3046        3.0  NaN  NaN  NaN  NaN    8.0   NaN   NaN   NaN   NaN
3047        NaN  1.0  NaN  NaN  NaN    NaN   6.0   NaN   NaN   NaN
3048        NaN  NaN  2.0  NaN  NaN    NaN   NaN   4.0   NaN   NaN
3049        NaN  NaN  NaN  3.0  NaN    NaN   NaN   NaN   2.0   NaN
3050        NaN  NaN  NaN  NaN  2.0    NaN   NaN   NaN   NaN   1.0

In [14]:
#values=Numeric
# index,columns="other" can be (categorical""qualitative"

# Cross Tabs
=> counting purpose

In [17]:
pd.crosstab(df['RaceID'],df['PitStops'])

PitStops  1  2  3
RaceID
3001      0  1  0
3002      0  0  1
3003      1  0  0
3004      0  1  0
3005      0  1  0
3006      0  0  1
3007      1  0  0
3008      0  1  0
3009      0  0  1
3010      0  1  0
3011      0  1  0
3012      0  0  1
3013      1  0  0
3014      0  1  0
3015      0  1  0
3016      0  0  1
3017      1  0  0
3018      0  1  0
3019      0  0  1
3020      0  1  0
3021      0  1  0
3022      0  0  1
3023      1  0  0
3024      0  1  0
3025      0  1  0
3026      0  0  1
3027      1  0  0
3028      0  1  0
3029      0  0  1
3030      0  1  0
3031      0  1  0
3032      0  0  1
3033      1  0  0
3034      0  1  0
3035      0  1  0
3036      0  0  1
3037      1  0  0
3038      0  1  0
3039      0  0  1
3040      0  1  0
3041      0  1  0
3042      0  0  1
3043      1  0  0
3044      0  1  0
3045      0  1  0
3046      0  0  1
3047      1  0  0
3048      0  1  0
3049      0  0  1
3050      0  1  0